pfpa/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers

from pfpaapp import views

apiRouter = routers.DefaultRouter()
apiRouter.register(r'users', views.UserViewSet)
apiRouter.register(r'groups', views.GroupViewSet)
apiRouter.register(r'sex', views.SexViewSet)
apiRouter.register(r'classslot', views.ClassSlotViewSet)
apiRouter.register(r'classoffergroup', views.ClassOfferGroupViewSet)
apiRouter.register(r'classoffer', views.ClassOfferViewSet)
apiRouter.register(r'teacher', views.TeacherViewSet)
apiRouter.register(r'wish', views.WishViewSet)
apiRouter.register(r'pupil', views.PupilViewSet)
apiRouter.register(r'classallocation', views.ClassAllocationViewSet)
apiRouter.register(r'optimizerrun', views.OptimizerRunViewSet)
apiRouter.register(r'optimizerresult', views.OptimizerResultViewSet)
apiRouter.register(r'wishcategory', views.WishCategoryViewSet)

urlpatterns = [
    path('', include('pfpaapp.urls')),
    path('api/', include((apiRouter.urls, 'api'))),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    url('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url('', include(('django_prometheus.urls', 'prometheus'))),
]

pfpaapp/urls.py
"""
pfpaapp URL configuration
"""

from django.conf.urls import url
from django.urls import path, include
from django.contrib.auth import views as auth_views
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from . import views

schema_view = get_schema_view(
    openapi.Info(
        title="Internal and External PFPA API",
        default_version='v1',
        description="This API exposes all components which the GUI also exposes.",
        contact=openapi.Contact(email="matrixfueller@gmail.com"),
        license=openapi.License(name="GNU GPLv3"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

app_name = 'pfpaapp'

account_patterns = [
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('overview', views.overview, name='overview'),
    path('password_change', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),
    path('password_change/done', auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    path('password_reset', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'),
         name='password_reset'),
    path('password_reset/done', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

wish_patterns = [
    path('', views.wishes_index),
    path('submit', views.wishes_submit, name='wishes_submit'),
    path('confirm', views.wishes_confirm, name='wishes_confirm'),
    path('edit', views.wishes_edit, name='wishes_edit'),
    path('show', views.wishes_show, name='wishes_show'),
]

urlpatterns = [
    path('', views.index, name='index'),
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('accounts/', include(account_patterns)),
    path('wishes/', include(wish_patterns))
]

pfpaapp/views.py
"""
This module contains all views which can be searches through in the UI.
"""
import logging
from datetime import date

from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect
from django.contrib.auth.models import Group
from rest_framework import viewsets, permissions

from pfpaapp.models import User, Sex, ClassSlot, ClassOffer, Teacher, Wish, Pupil, ClassAllocation, OptimizerRun
from pfpaapp.models import OptimizerResult, ClassOfferGroup, WishCategory
from pfpaapp.forms import WishForm, WishConfirmForm
from pfpaapp.serializers import UserSerializer, GroupSerializer, SexSerializer, ClassSlotSerializer
from pfpaapp.serializers import ClassOfferSerializer, TeacherSerializer, WishSerializer, PupilSerializer
from pfpaapp.serializers import ClassAllocationSerializer, OptimizerRunSerializer, OptimizerResultSerializer
from pfpaapp.serializers import ClassOfferGroupSerializer, WishCategorySerializer

logger = logging.getLogger(__name__)


def __build_navbar_context(request):
    """
    This fills the context with the objects needed to render the navbar correctly.

    :param request: The request coming from the user/browser.
    :return: The dictionary which contains either a pupil or a teacher if a user is authenticated. Otherwise it is
             empty.
    """
    context = {}
    if request.user.is_authenticated:
        current_user = request.user
        if Pupil.objects.filter(user=current_user).exists():
            context['pupil'] = Pupil.objects.get(user=current_user)
        elif Teacher.objects.filter(user=current_user).exists():
            context['teacher'] = Teacher.objects.get(user=current_user)
        else:
            logger.info('Neither a pupil nor a teacher has logged in. Affected username: %s', current_user)
    return context


def __build_bound_confirm_form(data_ids: dict):
    form_values = {'additum': data_ids.pop('additum', False)}
    for key in data_ids:
        if data_ids[key]:
            offer_id = data_ids[key]
            form_values.update({key: ClassOffer.objects.get(id=offer_id).name})
        else:
            form_values.update({key: ''})
    return form_values


def __generate_wish_dict(wish_form_instance):
    return {
        'additum': wish_form_instance.cleaned_data.get("additum", False),
        'firstchoice': wish_form_instance.cleaned_data.get("firstchoice", ""),
        'secondchoice': wish_form_instance.cleaned_data.get("secondchoice", ""),
        'thirdchoice': wish_form_instance.cleaned_data.get("thirdchoice", ""),
        'fourthchoice': wish_form_instance.cleaned_data.get("fourthchoice", ""),
        'firstexchangechoice': wish_form_instance.cleaned_data.get("firstexchangechoice", ""),
        'secondexchangechoice': wish_form_instance.cleaned_data.get("secondexchangechoice", ""),
        'exclusionchoice': wish_form_instance.cleaned_data.get("exclusionchoice", "")
    }


def __generate_wish_form_session_data(request, clean_wishes: dict):
    request.session['wish_form'] = {
        'additum': clean_wishes['additum'],
        'firstchoice': clean_wishes['firstchoice'].id if clean_wishes['firstchoice'] else "",
        'secondchoice': clean_wishes['secondchoice'].id if clean_wishes['secondchoice'] else "",
        'thirdchoice': clean_wishes['thirdchoice'].id if clean_wishes['thirdchoice'] else "",
        'fourthchoice': clean_wishes['fourthchoice'].id if clean_wishes['fourthchoice'] else "",
        'firstexchangechoice': clean_wishes['firstexchangechoice'].id if clean_wishes['firstexchangechoice'] else "",
        'secondexchangechoice': clean_wishes['secondexchangechoice'].id if clean_wishes['secondexchangechoice'] else "",
        'exclusionchoice': clean_wishes['exclusionchoice'].id if clean_wishes['exclusionchoice'] else "",
    }


def __generate_wish(session, field_name: str, pupil):
    try:
        offer_id = session['wish_form'][field_name]
        if not offer_id:
            return None
        offer_object = ClassOffer.objects.get(id=offer_id)
        try:
            offer_object.full_clean()
            logger.info("\"%s\" of pupil \"%s\" is valid.", field_name, pupil.user.username)
        except ValidationError:
            logger.warning("\"%s\" of user \"%s\" is invalid.", field_name, pupil.user.username)
        return Wish(classOffer=offer_object, pupil=pupil)
    except ClassOffer.DoesNotExist:
        return None


def index(request):
    """
    The landing page for users.

    :template:`pfpaapp/index.html`
    """
    context = {**__build_navbar_context(request)}
    return render(request, 'pfpaapp/index.html', context)


@login_required
def wishes_index(request):
    """
    This redirects to :view:`wishes_submit`
    """
    return redirect('wishes_submit')


@login_required
def wishes_submit(request):
    """
    This is the page where a pupil can submit its wishes.

    :template:`pfpaapp/wishes/submit.html`
    """
    context = __build_navbar_context(request)

    if context['pupil'].has_submitted_wishes():
        return redirect('pfpaapp:wishes_edit')

    if request.method == 'POST':
        # if this is a POST request we need to process the form data
        form = WishForm(request.POST, **{'user': request.user})
        # create a form instance and populate it with data from the request:
        if form.is_valid():
            clean_wish_dict = __generate_wish_dict(form)
            if clean_wish_dict['additum'] is None:
                # This should never happen since the form data is cleaned and optional fields get a value. If it happens
                # we show the user an error.
                form.add_error(None, "Unbekannter Fehler bei der Verarbeitung des Additum Wertes.")
            elif isinstance(clean_wish_dict['additum'], bool) and clean_wish_dict['additum']:
                if clean_wish_dict['firstchoice'] and clean_wish_dict['secondchoice'] \
                        and not (clean_wish_dict['thirdchoice']
                                 or clean_wish_dict['fourthchoice']
                                 or clean_wish_dict['firstexchangechoice']
                                 or clean_wish_dict['secondexchangechoice']
                                 or clean_wish_dict['exclusionchoice']):
                    __generate_wish_form_session_data(request, clean_wish_dict)
                    return redirect('pfpaapp:wishes_confirm')
                else:
                    # TODO: Error because wrong choice
                    pass
            elif isinstance(clean_wish_dict['additum'], bool) and not clean_wish_dict['additum']:
                if clean_wish_dict['firstchoice'] and clean_wish_dict['secondchoice']:
                    __generate_wish_form_session_data(request, clean_wish_dict)
                    return redirect('pfpaapp:wishes_confirm')
                else:
                    # TODO: Some error maybe. Think this through
                    pass
            else:
                # This should also never happen. Give the user a general error message.
                form.add_error(None, "Unbekannter Fehler bei der Verarbeitung der Wahldaten.")
    else:
        # if a GET (or any other method) we'll create a blank form
        form = WishForm(**{'user': request.user})
    context = {**context, **{'form': form}}
    return render(request, 'pfpaapp/wishes/submit.html', context)


@login_required
def wishes_confirm(request):
    """
    This is the page where a pupil confirms what he has chosen as wishes.

    :template:`pfpaapp/wishes/confirm.html`
    """
    # Check if the required session variable is there.
    if "wish_form" not in request.session:
        logger.info("No session for the form data not in wishes confirm!")
        return redirect("pfpaapp:wishes_submit")

    if request.method == 'POST':
        if Pupil.objects.filter(user=request.user).exists():
            pupil = Pupil.objects.get(user=request.user)
        else:
            return redirect('pfpaapp:index')

        if pupil.has_submitted_wishes():
            return redirect('pfpaapp:wishes_edit')

        if request.POST.get("back", None):
            return redirect("pfpaapp:wishes_submit")

        form = WishConfirmForm(request.POST)
        if form.is_valid():
            # Save to the Database
            # Don't uncomment save() calls before we are safe this works!
            current_data = __generate_wish_dict(form)
            session_data = __build_bound_confirm_form(request.session["wish_form"])
            if session_data == current_data:
                pupil.wish_additum = session_data["additum"]
                pupil.wish_submitted = date.today()
                try:
                    pupil.full_clean()
                    logger.info("Pupil is valid.")
                    pupil.save()
                except ValidationError:
                    logger.warning("Pupil is not valid.")
                    # TODO: Redirect to error page
                firstchoice = __generate_wish(request.session, "firstchoice", pupil)
                if firstchoice is not None:
                    firstchoice.category = WishCategory.objects.get(order=1)
                    firstchoice.save()
                    pass
                else:
                    # TODO: Redirect to error page
                    pass
                secondchoice = __generate_wish(request.session, "secondchoice", pupil)
                if secondchoice is not None:
                    secondchoice.category = WishCategory.objects.get(order=2)
                    secondchoice.save()
                    pass
                else:
                    # TODO: Redirect to error page
                    pass
                if not session_data["additum"]:
                    thirdchoice = __generate_wish(request.session, "thirdchoice", pupil)
                    if thirdchoice is not None:

pfpaapp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'pfpaapp/css/main.css' %}">
    <link rel="shortcut icon" type="image/ico" href="{% static 'pfpaapp/favicon.ico' %}"/>
</head>
<body>
{% include "navbar.html" %}
{% block content %}{% endblock %}
{% include "footer.html" %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
{% block additional_js %}{% endblock %}
</body>
</html>

pfpaapp/templates/footer.html
<footer class="footer">
    <div class="container">
        <span class="text-muted">Static Text</span>
        <a class="text-muted" href="https://gitlab.io/pfpa/pfpa">Gitlab</a>
        <a class="text-muted" href="https://pfpa.gitlab.io/docs/">Dokumentation</a>
        <a class="float-right text-muted" href="https://pfpa.gitlab.io">PFPA-Projekt</a>
    </div>
</footer>

pfpaapp/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'pfpaapp:index' %}">Sportwahl</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'pfpaapp:index' %}">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'pfpaapp:overview' %}">Übersicht</a>
            </li>
            {% if user.is_authenticated %}
                {% if pupil and not pupil.has_submitted_wishes %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pfpaapp:wishes_submit' %}">Wahl durchführen</a>
                    </li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Account
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if pupil and pupil.has_submitted_wishes %}
                            <a class="dropdown-item" href="{% url 'pfpaapp:wishes_show' %}">Wahl anzeigen</a>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'pfpaapp:password_change' %}">Passwort ändern</a>
                    </div>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pfpaapp:password_reset' %}">Passwort Reset</a>
                </li>
            {% endif %}
        </ul>
        <div class="my-2 my-lg-0">
            {% if user.is_authenticated %}
                <a href="{% url 'pfpaapp:logout' %}" class="btn btn-outline-success" role="button">Logout</a>
            {% else %}
                <a href="{% url 'pfpaapp:login' %}" class="btn btn-outline-success" role="button">Login</a>
            {% endif %}
        </div>
    </div>
</nav>

pfpaapp/templates/swagger-ui.html
<!DOCTYPE html>
<html>
  <head>
    <title>Swagger</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="//unpkg.com/swagger-ui-dist@3/swagger-ui.css" />
  </head>
  <body>
    <div id="swagger-ui"></div>
    <script src="//unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
    <script>
    const ui = SwaggerUIBundle({
        url: "{% url schema_url %}",
        dom_id: '#swagger-ui',
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIBundle.SwaggerUIStandalonePreset
        ],
        layout: "BaseLayout",
        requestInterceptor: (request) => {
          request.headers['X-CSRFToken'] = "{{ csrf_token }}"
          return request;
        }
      })
    </script>
  </body>
</html>